# Numpy

In [2]:
import numpy as np

In [4]:
rang1 = list(range(0,5))

In [6]:
nar1 = np.array(range)

In [7]:
type(nar1)

numpy.ndarray

In [8]:
mytr1 = [[1,2,3],[6,7,4],[2,4,1]]

In [9]:
np.array(mytr1)

array([[1, 2, 3],
       [6, 7, 4],
       [2, 4, 1]])

In [10]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
 # first num, second and how many nums between them
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
# rarefied square matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
# Rand num between 0 and 1 
np.random.rand(2)

array([0.36203698, 0.07060205])

In [26]:
np.random.rand(3,5)

array([[0.19061047, 0.1993382 , 0.86765545, 0.70434462, 0.5878453 ],
       [0.99500765, 0.49177427, 0.55948897, 0.8499212 , 0.61253394],
       [0.19427754, 0.48840005, 0.06711376, 0.03737444, 0.70448664]])

In [27]:
# Normal distribution
np.random.randn(5)

array([-0.5291638 ,  0.07930098,  0.69033113,  1.34135669,  2.33084167])

In [31]:
# Random int between a and b
np.random.randint(1,100)

12

In [35]:
np.random.randint(1,100,8)

array([54, 24, 37, 32, 17,  9, 84, 48])

In [43]:
arr = np.arange(1,10)

In [44]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr.reshape(9,1).shape

(9, 1)

In [51]:
ranarr = np.random.randint(1,100,20)

In [52]:
ranarr

array([80, 22, 69,  2, 85, 33, 29,  7, 32, 30, 46, 72, 42, 79,  4, 64, 48,
       90, 89, 59])

In [56]:
ranarr.max()

90

In [57]:
# Index of the max value
ranarr.argmax()

17

In [58]:
ranarr.min()

2

In [59]:
ranarr.argmin()

3

# Operations

In [60]:
arr2 = np.arange(0,10)

In [61]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# arr2 + arr - Error: They have different sizes
arr2 + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
arr2 * arr2 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [67]:
# Warning: couse arr2 has Zero - 0
arr2 / arr2 

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [68]:
1/arr2

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [69]:
arr2 ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [70]:
arr2 + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [71]:
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [72]:
np.exp(arr2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [73]:
np.sin(arr2)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [74]:
np.sin(arr2) / np.cos(arr2)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [75]:
np.log(arr2)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Indexing and Selectioning

In [77]:
arr3 = np.arange(0,11)

In [78]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr3[1]

1

In [80]:
arr3[1:4]

array([1, 2, 3])

In [81]:
arr3[:5]

array([0, 1, 2, 3, 4])

In [82]:
arr3[8:]

array([ 8,  9, 10])

In [83]:
arr3[0:5] = 100
arr3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [84]:
arr = np.arange(0,10)

In [85]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
slice_arr = arr[0:3]

In [92]:
slice_arr

array([0, 1, 2])

In [93]:
slice_arr[:] = 99

## It's called Brodcasting - via slice of array it's possible to change main array. Because slice to array - it's a poiter to nums in main array

In [95]:
# It,s 
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [96]:
arr_copy = arr.copy()

In [97]:
arr_copy

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [98]:
mat = np.array([[5,6,3], [2,8,4], [1,8,6]])

In [99]:
mat

array([[5, 6, 3],
       [2, 8, 4],
       [1, 8, 6]])

In [100]:
mat[0]

array([5, 6, 3])

In [101]:
mat[0][1]

6

In [102]:
mat

array([[5, 6, 3],
       [2, 8, 4],
       [1, 8, 6]])

In [110]:
mat[:2,1:]

array([[6, 3],
       [8, 4]])

In [113]:
mat[1:][:2] # Wrong too

array([[2, 8, 4],
       [1, 8, 6]])

## Conditional section

In [114]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [116]:
boll_arr = arr > 4

In [117]:
# Returning only where elemnts > 4
arr[boll_arr]

array([ 5,  6,  7,  8,  9, 10])

In [118]:
# Or
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])